// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: camiones.proto

package camiones

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Paquete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Paquete) Reset() {
	*x = Paquete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camiones_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Paquete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Paquete) ProtoMessage() {}

func (x *Paquete) ProtoReflect() protoreflect.Message {
	mi := &file_camiones_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Paquete.ProtoReflect.Descriptor instead.
func (*Paquete) Descriptor() ([]byte, []int) {
	return file_camiones_proto_rawDescGZIP(), []int{0}
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camiones_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_camiones_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_camiones_proto_rawDescGZIP(), []int{1}
}

var File_camiones_proto protoreflect.FileDescriptor

var file_camiones_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x63, 0x61, 0x6d, 0x69, 0x6f, 0x6e, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x63, 0x61, 0x6d, 0x69, 0x6f, 0x6e, 0x65, 0x73, 0x22, 0x09, 0x0a, 0x07, 0x70, 0x61,
	0x71, 0x75, 0x65, 0x74, 0x65, 0x22, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x32, 0xbf, 0x01, 0x0a, 0x08, 0x63, 0x61, 0x6d, 0x69, 0x6f, 0x6e, 0x65, 0x73, 0x12, 0x3e,
	0x0a, 0x13, 0x69, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x61, 0x72, 0x50, 0x72, 0x69, 0x6f, 0x72, 0x69,
	0x74, 0x61, 0x72, 0x69, 0x6f, 0x12, 0x11, 0x2e, 0x63, 0x61, 0x6d, 0x69, 0x6f, 0x6e, 0x65, 0x73,
	0x2e, 0x70, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x1a, 0x12, 0x2e, 0x63, 0x61, 0x6d, 0x69, 0x6f,
	0x6e, 0x65, 0x73, 0x2e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3a,
	0x0a, 0x0e, 0x69, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x61, 0x72, 0x52, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x12, 0x12, 0x2e, 0x63, 0x61, 0x6d, 0x69, 0x6f, 0x6e, 0x65, 0x73, 0x2e, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x12, 0x2e, 0x63, 0x61, 0x6d, 0x69, 0x6f, 0x6e, 0x65, 0x73, 0x2e,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x0c, 0x69, 0x6e,
	0x67, 0x72, 0x65, 0x73, 0x61, 0x72, 0x50, 0x79, 0x6d, 0x65, 0x12, 0x11, 0x2e, 0x63, 0x61, 0x6d,
	0x69, 0x6f, 0x6e, 0x65, 0x73, 0x2e, 0x70, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x1a, 0x12, 0x2e,
	0x63, 0x61, 0x6d, 0x69, 0x6f, 0x6e, 0x65, 0x73, 0x2e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x02, 0x50, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_camiones_proto_rawDescOnce sync.Once
	file_camiones_proto_rawDescData = file_camiones_proto_rawDesc
)

func file_camiones_proto_rawDescGZIP() []byte {
	file_camiones_proto_rawDescOnce.Do(func() {
		file_camiones_proto_rawDescData = protoimpl.X.CompressGZIP(file_camiones_proto_rawDescData)
	})
	return file_camiones_proto_rawDescData
}

var file_camiones_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_camiones_proto_goTypes = []interface{}{
	(*Paquete)(nil),  // 0: camiones.paquete
	(*Response)(nil), // 1: camiones.response
}
var file_camiones_proto_depIdxs = []int32{
	0, // 0: camiones.camiones.ingresarPrioritario:input_type -> camiones.paquete
	1, // 1: camiones.camiones.ingresarRetail:input_type -> camiones.response
	0, // 2: camiones.camiones.ingresarPyme:input_type -> camiones.paquete
	1, // 3: camiones.camiones.ingresarPrioritario:output_type -> camiones.response
	1, // 4: camiones.camiones.ingresarRetail:output_type -> camiones.response
	1, // 5: camiones.camiones.ingresarPyme:output_type -> camiones.response
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_camiones_proto_init() }
func file_camiones_proto_init() {
	if File_camiones_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_camiones_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Paquete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camiones_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_camiones_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_camiones_proto_goTypes,
		DependencyIndexes: file_camiones_proto_depIdxs,
		MessageInfos:      file_camiones_proto_msgTypes,
	}.Build()
	File_camiones_proto = out.File
	file_camiones_proto_rawDesc = nil
	file_camiones_proto_goTypes = nil
	file_camiones_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CamionesClient is the client API for Camiones service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CamionesClient interface {
	IngresarPrioritario(ctx context.Context, in *Paquete, opts ...grpc.CallOption) (*Response, error)
	IngresarRetail(ctx context.Context, in *Response, opts ...grpc.CallOption) (*Response, error)
	IngresarPyme(ctx context.Context, in *Paquete, opts ...grpc.CallOption) (*Response, error)
}

type camionesClient struct {
	cc grpc.ClientConnInterface
}

func NewCamionesClient(cc grpc.ClientConnInterface) CamionesClient {
	return &camionesClient{cc}
}

func (c *camionesClient) IngresarPrioritario(ctx context.Context, in *Paquete, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/camiones.camiones/ingresarPrioritario", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *camionesClient) IngresarRetail(ctx context.Context, in *Response, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/camiones.camiones/ingresarRetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *camionesClient) IngresarPyme(ctx context.Context, in *Paquete, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/camiones.camiones/ingresarPyme", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CamionesServer is the server API for Camiones service.
type CamionesServer interface {
	IngresarPrioritario(context.Context, *Paquete) (*Response, error)
	IngresarRetail(context.Context, *Response) (*Response, error)
	IngresarPyme(context.Context, *Paquete) (*Response, error)
}

// UnimplementedCamionesServer can be embedded to have forward compatible implementations.
type UnimplementedCamionesServer struct {
}

func (*UnimplementedCamionesServer) IngresarPrioritario(context.Context, *Paquete) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IngresarPrioritario not implemented")
}
func (*UnimplementedCamionesServer) IngresarRetail(context.Context, *Response) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IngresarRetail not implemented")
}
func (*UnimplementedCamionesServer) IngresarPyme(context.Context, *Paquete) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IngresarPyme not implemented")
}

func RegisterCamionesServer(s *grpc.Server, srv CamionesServer) {
	s.RegisterService(&_Camiones_serviceDesc, srv)
}

func _Camiones_IngresarPrioritario_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Paquete)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CamionesServer).IngresarPrioritario(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/camiones.camiones/IngresarPrioritario",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CamionesServer).IngresarPrioritario(ctx, req.(*Paquete))
	}
	return interceptor(ctx, in, info, handler)
}

func _Camiones_IngresarRetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Response)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CamionesServer).IngresarRetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/camiones.camiones/IngresarRetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CamionesServer).IngresarRetail(ctx, req.(*Response))
	}
	return interceptor(ctx, in, info, handler)
}

func _Camiones_IngresarPyme_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Paquete)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CamionesServer).IngresarPyme(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/camiones.camiones/IngresarPyme",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CamionesServer).IngresarPyme(ctx, req.(*Paquete))
	}
	return interceptor(ctx, in, info, handler)
}

var _Camiones_serviceDesc = grpc.ServiceDesc{
	ServiceName: "camiones.camiones",
	HandlerType: (*CamionesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ingresarPrioritario",
			Handler:    _Camiones_IngresarPrioritario_Handler,
		},
		{
			MethodName: "ingresarRetail",
			Handler:    _Camiones_IngresarRetail_Handler,
		},
		{
			MethodName: "ingresarPyme",
			Handler:    _Camiones_IngresarPyme_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "camiones.proto",
}
